"use client";
import { useEffect, useState } from "react";
import { formatMinorMoney, formatMinorMoneyGrouped } from "@/lib/financial-history";
import { DisclosureIcon } from "./disclosure-icon";
import { useLanguage } from "./language-provider";
import type { loadCollectionManagement } from "@/lib/collection-management";
type Data = Awaited<ReturnType<typeof loadCollectionManagement>>;
const emptyPlan = { id: "", title: "", playerName: "", budget: "", currency: "CNY", targetDate: "", notes: "" };
export function CollectionWorkspace() {
  const { locale, t } = useLanguage(), l = (zh: string, en: string) => locale === "en" ? en : zh;
  const [data, setData] = useState<Data | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const [wishFormOpen, setWishFormOpen] = useState(false);
  const [showArchived, setShowArchived] = useState(false), [limit, setLimit] = useState(50), [plan, setPlan] = useState(emptyPlan);
  async function refresh() { const response = await fetch("/api/collection-management"); const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result); }
  useEffect(() => { void refresh().catch(error => setError(String(error))); }, []);
  async function mutate(body: unknown) {
    setBusy(true); setError("");
    try { const response = await fetch("/api/collection-management", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); await refresh(); return true; }
    catch (error) { setError(error instanceof Error ? error.message : String(error)); return false; }
    finally { setBusy(false); }
  }
  const kinds = { images: l("补充卡图", "Add images"), purchase: l("补充购买记录", "Add purchase history"), valuation: l("补充估值", "Add valuation"), stale: l("更新过期估值", "Refresh valuation"), grading: l("跟进送评进度", "Follow up grading"), listed: l("检查在售状态", "Review listing") };
  const taskStatus: Record<string, string> = { open: l("待处理", "Open"), done: l("已完成", "Done"), snoozed: l("已延后", "Snoozed"), dismissed: l("已忽略", "Dismissed") };
  const wishStatus: Record<string, string> = { planned: l("待实现", "Planned"), acquired: l("已实现", "Acquired"), cancelled: l("已取消", "Cancelled") };
  const money = (minor: string, currency: string) => formatMinorMoneyGrouped(BigInt(minor), currency);
  const tasks = data?.tasks.filter(task => showArchived || task.state === "open") ?? [];
  return <div className="page management-page plans-page"><h1 className="sr-only">{l("计划", "Plans")}</h1>
    {error ? <p className="note-error" role="alert">{t(error)}</p> : null}
    {!data ? <p role="status">{l("加载中…", "Loading…")}</p> : <div className="plans-layout"><div className="plans-overview">
      <section className="panel management-section plans-digest"><div className="plans-section-head"><h2>{l("收藏摘要", "Collection digest")}</h2><label className="digest-period"><span className="sr-only">{l("统计周期", "Period")}</span><select disabled={busy} value={data.settings.digestCadence} onChange={event => void mutate({ action: "settings", ...data.settings, digestCadence: event.target.value })}><option value="weekly">{l("最近 7 天", "Last 7 days")}</option><option value="monthly">{l("最近 30 天", "Last 30 days")}</option></select></label></div><div className="summary-grid">{[[l("新增", "New"), data.digest.newCards], [l("购买", "Purchases"), data.digest.purchases], [l("出售", "Sales"), data.digest.sales], [l("估值", "Valuations"), data.digest.valuations]].map(([label, value]) => <div className="panel" key={label}><span>{label}</span><p className="h1">{value}</p></div>)}</div></section>
      <section className="panel management-section"><div className="title-row"><h2>{l("待整理", "Review queue")} · {tasks.length}</h2><label><input type="checkbox" checked={showArchived} onChange={event => setShowArchived(event.target.checked)} />{l("显示已处理", "Show handled reminders")}</label></div>{tasks.slice(0, limit).map(task => <article className="management-task" key={task.id}><div><strong>{kinds[task.kind]}</strong><a href={`/cards/${task.cardId}`}>{task.playerName} · {task.cardTitle}</a><small>{task.days} {l("天", "days")}{task.dateEstimated ? l("（起始日估算）", " (estimated start)") : ""} · {taskStatus[task.state] ?? l("未知状态", "Unknown status")}</small></div><div className="management-toolbar">{(task.state === "open" ? ["done", "snoozed", "dismissed"] : ["open"]).map(status => <button className="btn btn-secondary" disabled={busy} key={status} onClick={() => void mutate({ action: "task", id: task.id, fingerprint: task.fingerprint, status })}>{{ done: l("完成", "Done"), snoozed: l("延后 7 天", "Snooze 7 days"), dismissed: l("忽略", "Dismiss"), open: l("重新打开", "Reopen") }[status]}</button>)}</div></article>)}{tasks.length > limit ? <button className="btn btn-secondary" onClick={() => setLimit(limit + 50)}>{l("显示更多", "Show more")}</button> : null}</section>
      </div><section className="panel management-section plans-wishlist"><h2>{l("心愿单", "Wishlist")}</h2><details className="wish-disclosure" open={wishFormOpen} onToggle={event => setWishFormOpen(event.currentTarget.open)}><summary><span>{plan.id ? l("编辑", "Edit") : l("新增", "New")}</span><DisclosureIcon expanded={false} /></summary><form onSubmit={async event => { event.preventDefault(); if (await mutate({ action: "plan", ...plan })) { setPlan(emptyPlan); setWishFormOpen(false); } }}><div className="mapping-grid">{[["title", l("心愿名称", "Wish title")], ["playerName", l("卡片主体", "Subject")], ["budget", l("预算", "Budget")], ["currency", l("币种", "Currency")], ["targetDate", l("目标日期", "Target date")], ["notes", l("备注", "Notes")]].map(([field, label]) => <label key={field}>{label}{field === "currency" ? <select value={plan.currency} onChange={event => setPlan({ ...plan, currency: event.target.value })}><option>CNY</option><option>USD</option></select> : <input required={field === "title"} type={field === "targetDate" ? "date" : "text"} value={plan[field as keyof typeof plan]} onChange={event => setPlan({ ...plan, [field]: event.target.value })} />}</label>)}</div><button className="btn btn-primary" disabled={busy}>{plan.id ? l("保存心愿", "Save wish") : l("添加心愿", "Add wish")}</button>{plan.id ? <button className="btn btn-secondary" type="button" onClick={() => setPlan(emptyPlan)}>{l("取消编辑", "Cancel edit")}</button> : null}</form></details>
      <details className="wish-disclosure wish-list" open><summary><span>{l("列表", "List")} · {data.plans.length}</span><DisclosureIcon expanded={false} /></summary><div className="plans-budgets">{Object.entries(data.budgets).map(([currency, amount]) => <strong key={currency}>{money(amount, currency)}</strong>)}</div>{data.plans.map(item => <article className="management-task" key={item.id}><div><strong>{item.title}</strong><div className="wish-meta"><span>{item.playerName || "—"}</span><span className="numeric-value">{item.budgetMinor === null ? "—" : money(item.budgetMinor, item.currency)}</span><time dateTime={item.targetDate ?? undefined}>{item.targetDate || "—"}</time><span className="record-status">{wishStatus[item.status] ?? l("未知状态", "Unknown status")}</span></div><small>{item.notes}</small></div><div className="management-toolbar"><button className="btn btn-secondary" onClick={() => { setWishFormOpen(true); setPlan({ id: item.id, title: item.title, playerName: item.playerName ?? "", currency: item.currency, budget: item.budgetMinor === null ? "" : formatMinorMoney(BigInt(item.budgetMinor), item.currency).replace(item.currency + " ", ""), targetDate: item.targetDate ?? "", notes: item.notes ?? "" }); }}>{l("编辑", "Edit")}</button>{(item.status === "planned" ? ["acquired", "cancelled"] : ["planned"]).map(status => <button className="btn btn-secondary" disabled={busy} key={status} onClick={() => void mutate({ action: "plan-status", id: item.id, status })}>{{ acquired: l("已实现", "Acquired"), cancelled: l("取消心愿", "Cancel wish"), planned: l("重新计划", "Plan again") }[status]}</button>)}</div></article>)}</details></section>
    </div>}
  </div>;
}
