import { displayPortfolioFilterValue, portfolioFilterDefinitions } from "./portfolio-analysis-scope.ts";
import { emptyAllocation, normalizeConcentration } from "./portfolio-analysis-statistics.ts";
import type { PortfolioAnalysis, PortfolioAnalysisAction, PortfolioAnalysisAttentionItem, PortfolioAnalysisSection, PortfolioBreakdown, PortfolioCurrencySummary, PortfolioEvidence, PortfolioFinding, PortfolioFilterCriterion, PortfolioFilterField, PortfolioScorecardItem, PortfolioScope, PortfolioSnapshot } from "./portfolio-analysis-types.ts";

const portfolioCurrencies = ["CNY", "USD"] as const;
function money(value: number): number { return Math.round((Number.isFinite(value) ? value : 0) * 100) / 100; }
function safeText(value: unknown, maxLength = 1200): string { return typeof value === "string" ? value.trim().slice(0, maxLength) : ""; }
function objectRecord(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function boundedNumber(value: unknown, minimum: number, maximum: number, fallback = 0): number { const number = typeof value === "number" && Number.isFinite(value) ? value : fallback; return Math.max(minimum, Math.min(maximum, number)); }
function boundedCount(value: unknown, maximum: number): number { return Math.round(boundedNumber(value, 0, maximum)); }
function normalizeDateText(value: unknown): string | null { if (typeof value !== "string") return null; const date = new Date(value); return Number.isNaN(date.getTime()) ? null : date.toISOString(); }

function normalizeBreakdowns(value: unknown, maxItems: number, maxCount: number): PortfolioBreakdown[] {
  if (!Array.isArray(value)) return [];
  return value.slice(0, maxItems).map((item) => { const record = objectRecord(item); const rawValues = objectRecord(record.values); const values: Record<string, number> = {}; for (const currency of portfolioCurrencies) if (currency in rawValues) values[currency] = money(boundedNumber(rawValues[currency], 0, 1_000_000_000_000)); return { name: safeText(record.name, 80), count: boundedCount(record.count, maxCount), values }; }).filter((item) => item.name && item.count > 0);
}

function normalizePortfolioScope(value: unknown): PortfolioScope {
  const source = Array.isArray(objectRecord(value).criteria) ? objectRecord(value).criteria as unknown[] : [];
  const criteria = source.slice(0, Object.keys(portfolioFilterDefinitions).length).map((item): PortfolioFilterCriterion | null => { const record = objectRecord(item); const field = safeText(record.field, 40) as PortfolioFilterField; const valueText = safeText(record.value, 120); return field in portfolioFilterDefinitions && valueText ? { field, label: portfolioFilterDefinitions[field], value: displayPortfolioFilterValue(field, valueText) } : null; }).filter((item): item is PortfolioFilterCriterion => item !== null);
  return { isFiltered: criteria.length > 0, criteria };
}

function normalizeCurrencySummaries(value: unknown, cardCount: number): PortfolioCurrencySummary[] {
  if (!Array.isArray(value)) return [];
  const seen = new Set<string>();
  return value.slice(0, portfolioCurrencies.length).map((item) => { const record = objectRecord(item); const currency = safeText(record.currency, 3).toUpperCase(); if (!portfolioCurrencies.includes(currency as (typeof portfolioCurrencies)[number]) || seen.has(currency)) return null; seen.add(currency); const comparableCostBasis = money(boundedNumber(record.comparableCostBasis, 0, 1_000_000_000_000)); const comparableValue = money(boundedNumber(record.comparableValue, 0, 1_000_000_000_000)); const difference = money(comparableValue - comparableCostBasis); return { currency, purchaseAmount: money(boundedNumber(record.purchaseAmount, 0, 1_000_000_000_000)), refundAmount: money(boundedNumber(record.refundAmount, 0, 1_000_000_000_000)), salesAmount: money(boundedNumber(record.salesAmount, 0, 1_000_000_000_000)), expenseAmount: money(boundedNumber(record.expenseAmount, 0, 1_000_000_000_000)), netCashInvested: money(boundedNumber(record.netCashInvested, -1_000_000_000_000, 1_000_000_000_000)), latestValue: money(boundedNumber(record.latestValue, 0, 1_000_000_000_000)), valuedCardCount: boundedCount(record.valuedCardCount, cardCount), activeCostBasis: money(boundedNumber(record.activeCostBasis, 0, 1_000_000_000_000)), activeLatestValue: money(boundedNumber(record.activeLatestValue, 0, 1_000_000_000_000)), activeValuedCardCount: boundedCount(record.activeValuedCardCount, cardCount), comparableCardCount: boundedCount(record.comparableCardCount, cardCount), comparableCostBasis, comparableValue, unrealizedDifference: difference, unrealizedReturnRate: comparableCostBasis > 0 ? money(difference / comparableCostBasis * 100) : null }; }).filter((item): item is PortfolioCurrencySummary => item !== null);
}

export function normalizePortfolioSnapshot(value: unknown): PortfolioSnapshot {
  const snapshot = objectRecord(value); const cardCountValue = snapshot.cardCount;
  if (typeof cardCountValue !== "number" || !Number.isFinite(cardCountValue) || cardCountValue < 1 || cardCountValue > 100000) throw new Error("当前组合没有可分析的卡片，或卡片数量异常。");
  const cardCount = Math.round(cardCountValue); const activeCount = boundedCount(snapshot.activeCount, cardCount); const financials = objectRecord(snapshot.financials); const quality = objectRecord(snapshot.quality); const sources = Array.isArray(financials.valuationSources) ? financials.valuationSources : [];
  return { cardCount, activeCount, soldCount: boundedCount(snapshot.soldCount, cardCount), targetCount: boundedCount(snapshot.targetCount, cardCount), playerCount: boundedCount(snapshot.playerCount, cardCount), scope: normalizePortfolioScope(snapshot.scope), financials: { currencies: normalizeCurrencySummaries(financials.currencies, cardCount), transactionCoverageCount: boundedCount(financials.transactionCoverageCount, cardCount), expenseCoverageCount: boundedCount(financials.expenseCoverageCount, cardCount), valuationCoverageCount: boundedCount(financials.valuationCoverageCount, cardCount), freshValuationCount: boundedCount(financials.freshValuationCount, cardCount), staleValuationCount: boundedCount(financials.staleValuationCount, cardCount), latestValuationAt: normalizeDateText(financials.latestValuationAt), oldestLatestValuationAt: normalizeDateText(financials.oldestLatestValuationAt), valuationSources: sources.slice(0, 5).map((item) => { const record = objectRecord(item); return { name: safeText(record.name, 40), count: boundedCount(record.count, cardCount) }; }).filter((item) => item.name && item.count > 0), excludedComplexPositionCount: boundedCount(financials.excludedComplexPositionCount, activeCount) }, quality: { gradedCount: boundedCount(quality.gradedCount, activeCount), rookieCount: boundedCount(quality.rookieCount, activeCount), autographCount: boundedCount(quality.autographCount, activeCount), patchCount: boundedCount(quality.patchCount, activeCount), serialNumberedCount: 0, gradingCompanies: [], grades: [], autoTypes: [], patchTypes: [] }, sports: normalizeBreakdowns(snapshot.sports, 10, cardCount), players: normalizeBreakdowns(snapshot.players, 12, cardCount), statuses: normalizeBreakdowns(snapshot.statuses, 10, cardCount), allocation: emptyAllocation(), concentration: normalizeConcentration(snapshot.concentration, portfolioCurrencies), coverage: { imageCount: 0, imageCoverageCount: 0, publicDescriptionCoverageCount: 0, coreFieldCompletenessAverage: 0, incompleteCardCount: cardCount }, timeSeries: { purchases: [], sales: [], expenses: [], valuations: [] }, attentionItems: [], topPositions: [] };
}

function normalizeEvidence(value: unknown): PortfolioEvidence[] { if (!Array.isArray(value)) return []; return value.map((item) => { const record = objectRecord(item); const sourcePath = safeText(record.sourcePath, 120); const label = safeText(record.label, 120); const evidenceValue = safeText(record.value, 180); return sourcePath && label && evidenceValue ? { sourcePath, label, value: evidenceValue } : null; }).filter((item): item is PortfolioEvidence => item !== null).slice(0, 3); }
function normalizeFindings(value: unknown): PortfolioFinding[] { if (!Array.isArray(value)) return []; return value.map((item) => { const record = objectRecord(item); const title = safeText(record.title, 160); const content = safeText(record.content, 240); return title && content ? { title, content, confidence: record.confidence === "high" || record.confidence === "low" ? record.confidence : "medium", dataSufficiency: record.dataSufficiency === "sufficient" || record.dataSufficiency === "insufficient" ? record.dataSufficiency : "partial", evidence: normalizeEvidence(record.evidence) } : null; }).filter((item): item is PortfolioFinding => item !== null).slice(0, 3); }
function normalizeScorecardItem(value: unknown, fallbackText: string): PortfolioScorecardItem { const record = objectRecord(value); return { score: Math.round(boundedNumber(record.score, 0, 100)), explanation: safeText(record.explanation, 240) || fallbackText, dataSufficiency: record.dataSufficiency === "sufficient" || record.dataSufficiency === "insufficient" ? record.dataSufficiency : "partial", evidence: normalizeEvidence(record.evidence) }; }
function normalizeAnalysisSection(value: unknown): PortfolioAnalysisSection { const record = objectRecord(value); return { findings: normalizeFindings(record.findings), dataSufficiency: record.dataSufficiency === "sufficient" || record.dataSufficiency === "insufficient" ? record.dataSufficiency : "partial" }; }
function normalizeAnalysisAttentionItems(value: unknown): PortfolioAnalysisAttentionItem[] { if (!Array.isArray(value)) return []; return value.map((item) => { const record = objectRecord(item); const title = safeText(record.title, 160); const reason = safeText(record.reason, 240); return title && reason ? { priority: record.priority === "high" || record.priority === "low" ? record.priority : "medium", title, reason, affectedCount: boundedCount(record.affectedCount, 100000), sourcePath: safeText(record.sourcePath, 120) || null } : null; }).filter((item): item is PortfolioAnalysisAttentionItem => item !== null).slice(0, 5); }
function normalizeAnalysisActions(value: unknown): PortfolioAnalysisAction[] { if (!Array.isArray(value)) return []; return value.map((item, index) => { const record = objectRecord(item); const action = safeText(record.action, 240); const reason = safeText(record.reason, 240); const expectedBenefit = safeText(record.expectedBenefit, 240); return action && reason && expectedBenefit ? { priority: boundedCount(record.priority, 99) || index + 1, action, reason, expectedBenefit, sourcePath: safeText(record.sourcePath, 120) || null } : null; }).filter((item): item is PortfolioAnalysisAction => item !== null).slice(0, 5); }

export function normalizePortfolioAnalysis(value: unknown): PortfolioAnalysis {
  if (!value || typeof value !== "object") throw new Error("AI analysis result is invalid.");
  const record = value as Record<string, unknown>; const nested = record.analysis && typeof record.analysis === "object" ? record.analysis as Record<string, unknown> : record;
  if (nested.analysisVersion !== 2) throw new Error("AI 分析协议版本无效。");
  const executiveSummary = objectRecord(nested.executiveSummary); const scorecard = objectRecord(nested.scorecard); const sections = objectRecord(nested.sections);
  const scorecardKeys = ["structure", "financialEfficiency", "collectibleQuality", "liquidity", "dataCompleteness"] as const; const sectionKeys = ["structure", "financials", "collectibleQuality", "liquidity", "dataQuality"] as const;
  if (!safeText(executiveSummary.positioning, 120) || !safeText(executiveSummary.summary, 900) || scorecardKeys.some((key) => !Object.hasOwn(scorecard, key)) || sectionKeys.some((key) => !Object.hasOwn(sections, key))) throw new Error("AI 分析协议缺少新版报告必要内容。");
  return { analysisVersion: 2, executiveSummary: { overallScore: Math.round(boundedNumber(executiveSummary.overallScore, 0, 100)), positioning: safeText(executiveSummary.positioning, 120), summary: safeText(executiveSummary.summary, 900), confidence: executiveSummary.confidence === "high" || executiveSummary.confidence === "low" ? executiveSummary.confidence : "medium", dataSufficiency: executiveSummary.dataSufficiency === "sufficient" || executiveSummary.dataSufficiency === "insufficient" ? executiveSummary.dataSufficiency : "partial" }, scorecard: Object.fromEntries(scorecardKeys.map((key) => [key, normalizeScorecardItem(scorecard[key], "暂无判断")])) as PortfolioAnalysis["scorecard"], sections: Object.fromEntries(sectionKeys.map((key) => [key, normalizeAnalysisSection(sections[key])])) as PortfolioAnalysis["sections"], attentionItems: normalizeAnalysisAttentionItems(nested.attentionItems), actionItems: normalizeAnalysisActions(nested.actionItems) };
}
